import json
import os
import networkx as nx
from pyvis.network import Network

class KGVisualizer:
    def __init__(self, input_data):
        """
        Initializes the visualizer. 
        Accepts either a path to the JSON file or a pre-built NetworkX graph.
        """
        if isinstance(input_data, str) and os.path.exists(input_data):
            self.nx_graph = self._build_graph_from_json(input_data)
        elif hasattr(input_data, 'nodes'):
            self.nx_graph = input_data
        else:
            raise ValueError("Input must be a valid path to the JSON graph or a NetworkX graph.")

    def _build_graph_from_json(self, filepath):
        """Parses the generated taxonomy JSON into a NetworkX DiGraph."""
        G = nx.DiGraph()
        
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        # 1. Add Nodes
        for kb_id, node_props in data.get("nodes", {}).items():
            G.add_node(kb_id, **node_props)
            
        # 2. Add Edges
        for edge in data.get("edges", []):
            G.add_edge(
                edge["source"], 
                edge["target"], 
                relation=edge.get("relation", "subclass"),
                context=edge.get("context", "")
            )
            
        return G

    def visualize(self, output_file="knowledge_graph.html"):
        """
        Generates an interactive HTML file using PyVis.
        """
        # Create PyVis network
        net = Network(height="800px", width="100%", directed=True, notebook=False)
        net.force_atlas_2based(gravity=-50, central_gravity=0.01, spring_length=100, spring_strength=0.08)

        # --- ADD NODES ---
        for n, d in self.nx_graph.nodes(data=True):
            # Extract properties from our JSON schema
            label = d.get('canonical_label', n)
            kb_source = d.get('kb_source', 'unknown')
            aliases = d.get('aliases', [])
            
            # Styling based on Knowledge Base Source
            if kb_source == 'oewn':
                color = "#97C2FC"  # Blue for WordNet
                shape = "dot"
            elif kb_source == 'wikidata':
                color = "#97FCA4"  # Green for Wikidata
                shape = "square"
            else:
                color = "#CCCCCC"  # Gray fallback
                shape = "dot"

            # Hover Tooltip
            title_html = (
                f"<b>ID:</b> {n}<br>"
                f"<b>Label:</b> {label}<br>"
                f"<b>Source:</b> {kb_source.upper()}<br>"
                f"<b>Aliases:</b> {', '.join(aliases) if aliases else 'None'}"
            )

            net.add_node(
                n, 
                label=label, 
                title=title_html, 
                color=color, 
                shape=shape,
                size=20
            )

        # --- ADD EDGES ---
        for u, v, d in self.nx_graph.edges(data=True):
            rel_type = d.get('relation', 'subclass')
            context = d.get('context', '')

            # Styling based on Relationship Type
            if rel_type == "property":
                color = "#FF9900"  # Orange for properties/roles
                dashes = True
            else:
                color = "#2B7CE9"  # Default Blue for strict subclasses
                dashes = False

            # Hover Tooltip for edges (shows the definition)
            edge_title = f"<b>Relation:</b> {rel_type.upper()}<br><b>Context:</b> {context}"

            net.add_edge(
                u, v, 
                title=edge_title, 
                color=color, 
                label=rel_type, 
                dashes=dashes,
                arrows='to'
            )

        # Adds UI controls to adjust physics dynamically in the browser
        net.show_buttons(filter_=['physics'])
        
        # Save and display
        net.write_html(output_file)
        print(f"Interactive graph saved to: {output_file}")
        
        # Depending on your PyVis version/environment, opening might require os.startfile
        try:
            import webbrowser
            webbrowser.open(f"file://{os.path.abspath(output_file)}")
        except Exception:
            pass


if __name__ == "__main__":
    # Point this to the JSON file generated by the WordNet/Wikidata builder scripts
    JSON_PATH = "taxonomy_graph.json"
    
    if os.path.exists(JSON_PATH):
        visualizer = KGVisualizer(JSON_PATH)
        visualizer.visualize("taxonomy_visualization.html")
    else:
        print(f"Cannot find {JSON_PATH}. Run the populator scripts first!")